INSERT INTO flashcard (name, description)
VALUES
    ("Rule 1", "Wait until the way is clear before entering the intersection."),
("Rule 2", "Slow down, drive with extra caution and watch for children."),
("Rule 3", "Stop if necessary and go only when the way is clear."),
("Rule 4", "Slow down and look both ways for trains. Be prepared to stop."),
("Rule 5", "This road is an official bicycle route. Watch for cyclists and be prepared to share the road with them."),
("Rule 6", "You may park in the area between the signs during the times posted.  (Used in pairs or groups.)"),
("Rule 7", "Snowmobiles may use this road."),
("Rule 8", "Do not enter this road."),
("Rule 9", "Do not stop in the area between the signs. This means you may not stop your vehicle in this area, even for a moment. (Used in pairs or groups.)"),
("Rule 10", "Do not stand in the area between the signs. This means you may not stop your vehicle in this area except while loading or unloading passengers.  (Used in pairs or groups.)"),
("Rule 11", "Do not park in the area between the signs. This means you may not stop your vehicle except to load or unload passengers or merchandise. (Used in pairs or groups.)"),
("Rule 12", "Do not turn left at the intersection."),
("Rule 13", "Do not drive through the intersection."),
("Rule 14", "Do not turn to go in the opposite direction. (U-turn)"),
("Rule 15", "Do not turn right when facing a red light at the intersection."),
("Rule 16", "Do not turn left during the times shown."),
("Rule 17", "This parking space is only for vehicles displaying a valid Accessible Parking Permit."),
("Rule 18", "No bicycles allowed on this road."),
("Rule 19", "No pedestrians allowed on this road."),
("Rule 20", "Keep to the right of the traffic island."),
("Rule 21", "Speed limit changes ahead."),
("Rule 22", "Do not pass on this road."),
("Rule 23", "Slow traffic on multi-lane roads must keep right."),
("Rule 24", "Indicates areas where the community has identified that there is a special risk to pedestrians. Traffic related offences committed within the zone are subject to increased fines."),
("Rule 25", "The speed limit in this zone is lower during school hours. Observe the speed limit shown when the yellow lights are flashing."),
("Rule 26", "Stop for school bus when signals are flashing."),
("Rule 27", "This sign is installed on multi-lane highways with no centre median divider. It informs drivers approaching from both directions that they must stop for a school bus when its signal lights are flashing."),
("Rule 28", "These signs, above the road or on the pavement before an intersection, tell drivers the direction they must travel. For example: the driver in lane one must turn left; the driver in lane two must turn left or go straight ahead; and the driver in lane three must turn right."),
("Rule 29", "Traffic may travel in one direction only."),
("Rule 30", "This is a pedestrian crossover. Be prepared to stop and yield right-of-way to pedestrians."),
("Rule 31", "This sign, above the road or on the ground, means the lane is only for two-way left turns."),
("Rule 32", "This sign reserves curb area for vehicles displaying a valid Accessible Person Parking Permit picking up and dropping off passengers with disabilities."),
("Rule 33", "These signs mean lanes are only for specific types of vehicles, either all the time or during certain hours. Different symbols are used for the different types of vehicles. They include: buses, taxis, vehicles with three or more people and bicycles."),
("Rule 34", "Keep to the right lane except when passing on two-lane sections where climbing or passing lanes are provided."),
("Rule 35", "This sign on the back of transit buses serves as a reminder to motorists of the law requiring vehicles approaching a bus stopped at a dedicated Bus Stop to yield to the bus, once the bus has signalled its intent to return to the lane."),
("Rule 36", "Road forks to the right."),
("Rule 37", "Marks a zone within which school buses load or unload passengers without using the red alternating lights and stop arm."),
("Rule 38", "Only public vehicles such as buses, or passenger vehicles carrying a specified minimum number of passengers, may use this lane."),
("Rule 39", "Vehicles cannot change lanes into or out of a high-occupancy vehicle lane in this area."),
("Rule 40", "Narrow bridge ahead."),
("Rule 41", "Road branching off ahead."),
("Rule 42", "Intersection ahead. The arrow shows which direction of traffic has the right-of-way."),
("Rule 43", "Roundabout Ahead. Reduce Speed. The counter-clockwise arrows show the direction of vehicle traffic within the roundabout."),
("Rule 44", "Drivers on the sideroad at the intersection ahead don't have a clear view of traffic."),
("Rule 45", "Pavement narrows ahead."),
("Rule 46", "Slight bend or curve in the road ahead."),
("Rule 47", "Posted under a curve warning, this sign shows the maximum safe speed for the curve."),
("Rule 48", "Sharp bend or turn in the road ahead."),
("Rule 49", "Chevron (arrowhead) signs are posted in groups to guide drivers around sharp curves in the road."),
("Rule 50", "Winding road ahead."),
("Rule 51", "The bridge ahead lifts or swings to let boats pass."),
("Rule 52", "Paved surface ends ahead."),
("Rule 53", "Bicycle crossing ahead."),
("Rule 54", "Stop sign ahead. Slow down."),
("Rule 55", "Share the road with oncoming traffic."),
("Rule 56", "Pavement is slippery when wet. Slow down and drive with caution."),
("Rule 57", "Hazard close to the edge of the road. The downward lines show the side on which you may safely pass."),
("Rule 58", "Divided highway begins: traffic travels in both directions on separated roads ahead. Keep to the right-hand road. Each road carries one-way traffic."),
("Rule 59", "Right lane ends ahead. If you are in the right-hand lane, you must merge safely with traffic in the lane to the left."),
("Rule 60", "Traffic lights ahead. Slow down."),
("Rule 61", "Steep hill ahead. You may need to use a lower gear."),
("Rule 62", "Two roads going in the same direction are about to join into one.  Drivers on both roads are equally responsible for seeing that traffic merges smoothly and safely."),
("Rule 63", "Snowmobiles cross this road."),
("Rule 64", "Divided highway ends: traffic travels in both directions on the same road ahead. Keep to the right-hand road."),
("Rule 65", "Underpass ahead. Take care if you are driving a tall vehicle. Sign shows how much room you have."),
("Rule 66", "Bump or uneven pavement on the road ahead. Slow down and keep control of your vehicle."),
("Rule 67", "Railway crossing ahead. Be alert for trains. This sign also shows the angle at which the railway tracks cross the road."),
("Rule 68", "Sharp turn or bend in the road in the direction of the arrow. The checkerboard border warns of danger. Slow down; be careful."),
("Rule 69", "Deer regularly cross this road; be alert for animals."),
("Rule 70", "Truck entrance on the right side of the road ahead. If the sign shows the truck on the left, the entrance is on the left side of the road."),
("Rule 71", "Shows maximum safe speed on ramp."),
("Rule 72", "Watch for pedestrians and be prepared to share the road with them."),
("Rule 73", "Watch for fallen rock and be prepared to avoid a collision."),
("Rule 74", "There may be water flowing over the road."),
("Rule 75", "This sign warns you that you are coming to a hidden school bus stop. Slow down, drive with extra caution, watch for children and for a school bus with flashing red lights."),
("Rule 76", "Indicates an upcoming bus entrance on the right and vehicles should be prepared to yield to buses entering the roadway."),
("Rule 77", "Indicates an upcoming fire truck entrance on the right and vehicles should be prepared to yield to fire trucks entering the roadway."),
("Rule 78", "These signs warn of a school crossing. Watch for children and follow the directions of the crossing guard or school safety patroller."),
("Rule 79", "Construction work one kilometre ahead."),
("Rule 80", "Road work ahead."),
("Rule 81", "Survey crew working on the road ahead."),
("Rule 82", "Traffic control person ahead. Drive slowly and watch for instructions."),
("Rule 83", "You are entering a construction zone. Drive with extra caution and be prepared for a lower speed limit."),
("Rule 84", "Temporary detour from normal traffic route."),
("Rule 85", "Flashing lights on the arrows show the direction to follow."),
("Rule 86", "Pavement has been milled or grooved. Your vehicle's stopping ability may be affected so obey the speed limit and drive with extra caution.  Motorcyclists may experience reduced traction on these surfaces."),
("Rule 87", "Lane ahead is closed for roadwork. Obey the speed limit and merge with traffic in the open lane."),
("Rule 88", "Closed lane. Adjust speed to merge with traffic in lane indicated by arrow."),
("Rule 89", "Do not pass the pilot vehicle or pace vehicle bearing this sign."),
("Rule 90", "Reduce speed and be prepared to stop."),
("Rule 91", "Follow detour marker until you return to regular route."),
("Rule 92", "Enforces doubling the HTA fines for speeding in a designated construction zone when there are workers present."),
("Rule 93", "Shows directions to nearby towns and cities."),
("Rule 94", "Shows the distances in kilometres to towns and cities on the road."),
("Rule 95", "Various exit signs are used on freeways. In urban areas, many exit ramps have more than one lane. Overhead and ground-mounted signs help drivers choose the correct lane to exit or stay on the freeway."),
("Rule 96", "Advance signs use arrows to show which lanes lead off the freeway.  Signs are also posted at the exit."),
("Rule 97", "Sometimes one or more lanes may lead off the freeway. The arrows matching the exit lanes are shown on the advance sign in a yellow box with the word ‘exit' under them."),
("Rule 98", "Freeway interchanges or exits have numbers that correspond to the distance from the beginning of the freeway. For example, interchange number 204 on Highway 401 is 204 kilometres from Windsor, where the freeway begins.  Distances can be calculated by subtracting one interchange number from another."),
("Rule 99", "The term 'VIA' is used to describe the roads that must be followed to reach a destination."),
("Rule 100", "Shows the upcoming roundabout exits and where they will take you."),
("Rule 101", "These signs change according to traffic conditions to give drivers current information on delays and lane closures ahead."),
("Rule 102", "Shows off-road facilities such as hospitals, airports, universities or carpool lots."),
("Rule 103", "Shows route to passenger railway station."),
("Rule 104", "Shows route to airport."),
("Rule 105", "Shows facilities that are accessible by wheelchair."),
("Rule 106", "D sign – Oversize load")
;
